camunda.bpm:
  admin-user:
    id: admin
    password: admin
  client:
    base-url: http://localhost:8080/engine-rest # The URL pointing to the Camunda Platform Runtime REST API
    async-response-timeout: 1000 # Defines the maximum duration of the long-polling request
    worker-id: spring-boot-client # Identifies the worker towards the Engine
    #      basic-auth: # Configure if REST API is secured with basic authentication
    #        username: my-username
    #        password: my-password

spring:
  datasource:
    url: jdbc:h2:file:../camundaDB
#    username: sa
#    password: password

email:
  host: mail.fh-muenster.de
  sender: donotreply@fh-muenster.de










